//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Report_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRM_conn : DbContext
    {
        public SRM_conn()
            : base("name=SRM_conn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Semister_Master> tbl_Semister_Master { get; set; }
        public virtual DbSet<tbl_Semister_Subject_Map> tbl_Semister_Subject_Map { get; set; }
        public virtual DbSet<tbl_Student_Master> tbl_Student_Master { get; set; }
        public virtual DbSet<tbl_Student_Report> tbl_Student_Report { get; set; }
        public virtual DbSet<tbl_Subject_Master> tbl_Subject_Master { get; set; }
        public virtual DbSet<tbl_Year_Master> tbl_Year_Master { get; set; }
    }
}
