//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Report_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Semister_Subject_Map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Semister_Subject_Map()
        {
            this.tbl_Student_Report = new HashSet<tbl_Student_Report>();
        }
    
        public int Sem_Subject_Id { get; set; }
        public int Semister_Id { get; set; }
        public int Subject_Id { get; set; }
        public Nullable<int> Max_Score { get; set; }
    
        public virtual tbl_Semister_Master tbl_Semister_Master { get; set; }
        public virtual tbl_Subject_Master tbl_Subject_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Student_Report> tbl_Student_Report { get; set; }
    }
}
