//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Report_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Student_Master()
        {
            this.tbl_Student_Report = new HashSet<tbl_Student_Report>();
        }
    
        public int Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Email { get; set; }
        public string Student_Mobile { get; set; }
        public Nullable<System.DateTime> Student_DOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Student_Report> tbl_Student_Report { get; set; }
    }
}
