//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Report_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student_Report
    {
        public int Report_Id { get; set; }
        public int Student_Id { get; set; }
        public int Sem_Subject_Id { get; set; }
        public Nullable<int> User_Score { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual tbl_Semister_Subject_Map tbl_Semister_Subject_Map { get; set; }
        public virtual tbl_Student_Master tbl_Student_Master { get; set; }
    }
}
